@baseUrl = http://localhost:3002/api

### List all encryptions
GET {{baseUrl}}/encryptions HTTP/1.1
### list notes
GET {{baseUrl}}/notes HTTP/1.1
### get note by id
GET {{baseUrl}}/notes/14 HTTP/1.1
### get note by id decrypted
GET {{baseUrl}}/notes/14?decrypt=true HTTP/1.1
### add note
POST {{baseUrl}}/notes HTTP/1.1
content-type: application/json

{
    "message": "direct text",
    "encryption": 1
}
### update note
PATCH {{baseUrl}}/notes HTTP/1.1
content-type: application/json

{
    "id": 8,
    "message": "direct text 55",
    "encryption": 1,
    "encName": "backwards"
}
### delete note
DELETE {{baseUrl}}/notes/7 HTTP/1.1